import { AnimaKid, NaturalMushroom, VirtualWorlds } from "../images/images";


export const artistTabView = [
  [
    {
      nft: "Distinct Galaxy",
      nftImg: NaturalMushroom,
      creator: "Anima Kid",
      creatorImg: AnimaKid,
      price: "1.63",
      highestBid: "0.33",
    },
    {
      nft: "Distinct Galaxy",
      nftImg: NaturalMushroom,
      creator: "Anima Kid",
      creatorImg: AnimaKid,
      price: "1.63",
      highestBid: "0.33",
    },
    {
      nft: "Distinct Galaxy",
      nftImg: NaturalMushroom,
      creator: "Anima Kid",
      creatorImg: AnimaKid,
      price: "1.63",
      highestBid: "0.33",
    },
    {
      nft: "Distinct Galaxy",
      nftImg: NaturalMushroom,
      creator: "Anima Kid",
      creatorImg: AnimaKid,
      price: "1.63",
      highestBid: "0.33",
    },
    {
      nft: "Distinct Galaxy",
      nftImg: NaturalMushroom,
      creator: "Anima Kid",
      creatorImg: AnimaKid,
      price: "1.63",
      highestBid: "0.33",
    },
    {
      nft: "Distinct Galaxy",
      nftImg: NaturalMushroom,
      creator: "Anima Kid",
      creatorImg: AnimaKid,
      price: "1.63",
      highestBid: "0.33",
    },
    {
      nft: "Distinct Galaxy",
      nftImg: NaturalMushroom,
      creator: "Anima Kid",
      creatorImg: AnimaKid,
      price: "1.63",
      highestBid: "0.33",
    },
    {
      nft: "Distinct Galaxy",
      nftImg: NaturalMushroom,
      creator: "Anima Kid",
      creatorImg: AnimaKid,
      price: "1.63",
      highestBid: "0.33",
    },
  ],
  [
    {
      nft: "ColorfulDog",
      nftImg: NaturalMushroom,
      creator: "Anima Kid",
      creatorImg: AnimaKid,
      price: "1.63",
      highestBid: "0.33",
    },
    {
      nft: "ColorfulDog",
      nftImg: NaturalMushroom,
      creator: "Anima Kid",
      creatorImg: AnimaKid,
      price: "1.63",
      highestBid: "0.33",
    },
    {
      nft: "ColorfulDog",
      nftImg: NaturalMushroom,
      creator: "Anima Kid",
      creatorImg: AnimaKid,
      price: "1.63",
      highestBid: "0.33",
    },
    {
      nft: "ColorfulDog",
      nftImg: NaturalMushroom,
      creator: "Anima Kid",
      creatorImg: AnimaKid,
      price: "1.63",
      highestBid: "0.33",
    },
    {
      nft: "ColorfulDog",
      nftImg: NaturalMushroom,
      creator: "Anima Kid",
      creatorImg: AnimaKid,
      price: "1.63",
      highestBid: "0.33",
    },
    {
      nft: "ColorfulDog",
      nftImg: NaturalMushroom,
      creator: "Anima Kid",
      creatorImg: AnimaKid,
      price: "1.63",
      highestBid: "0.33",
    },
    {
      nft: "ColorfulDog",
      nftImg: NaturalMushroom,
      creator: "Anima Kid",
      creatorImg: AnimaKid,
      price: "1.63",
      highestBid: "0.33",
    },
    {
      nft: "ColorfulDog",
      nftImg: NaturalMushroom,
      creator: "Anima Kid",
      creatorImg: AnimaKid,
      price: "1.63",
      highestBid: "0.33",
    },
  ],
  [
    {
      nft: "Life on Edena",
      nftImg: VirtualWorlds,
      creator: "Anima Kid",
      creatorImg: AnimaKid,
      price: "1.63",
      highestBid: "0.33",
    },
    {
      nft: "Life on Edena",
      nftImg: VirtualWorlds,
      creator: "Anima Kid",
      creatorImg: AnimaKid,
      price: "1.63",
      highestBid: "0.33",
    },
    {
      nft: "Life on Edena",
      nftImg: VirtualWorlds,
      creator: "Anima Kid",
      creatorImg: AnimaKid,
      price: "1.63",
      highestBid: "0.33",
    },
    {
      nft: "Life on Edena",
      nftImg: VirtualWorlds,
      creator: "Anima Kid",
      creatorImg: AnimaKid,
      price: "1.63",
      highestBid: "0.33",
    },
    {
      nft: "Life on Edena",
      nftImg: VirtualWorlds,
      creator: "Anima Kid",
      creatorImg: AnimaKid,
      price: "1.63",
      highestBid: "0.33",
    },
    {
      nft: "Life on Edena",
      nftImg: VirtualWorlds,
      creator: "Anima Kid",
      creatorImg: AnimaKid,
      price: "1.63",
      highestBid: "0.33",
    },
    {
      nft: "Life on Edena",
      nftImg: VirtualWorlds,
      creator: "Anima Kid",
      creatorImg: AnimaKid,
      price: "1.63",
      highestBid: "0.33",
    },
    {
      nft: "Life on Edena",
      nftImg: VirtualWorlds,
      creator: "Anima Kid",
      creatorImg: AnimaKid,
      price: "1.63",
      highestBid: "0.33",
    },
  ],
];


export const artistTabContent = [
  { index: 0, label: "Created", content: artistTabView[0] },
  { index: 1, label: "Owned", content: artistTabView[1] },
  { index: 2, label: "Collection", content: artistTabView[2] },
];